language: python
python:
    - 2.6
    - 2.7
    - pypy
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - apt-get -y install libev
    - pip install --use-mirrors -r test-requirements.pip
services:
  - rabbitmq
script: nosetests -c nose.cfg
