language: python
python:
    - 2.6
    - 2.7
    - pypy
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libev-dev
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install pyev; fi
    - pip install --use-mirrors -r test-requirements.pip
services:
  - rabbitmq
script: nosetests -c nose.cfg
